# Generated by Django 4.2.1 on 2023-05-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_cover/')),
                ('book', models.FileField(upload_to='books/')),
                ('description', models.TextField()),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('ratings', models.PositiveIntegerField(default=0)),
                ('rated', models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature'), ('R', 'Restricted')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='authentication.profile')),
                ('downloaded_books', models.ManyToManyField(blank=True, related_name='downloaded_by', to='authentication.profile')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_books', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Self-Help', 'Self-Help')], max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_review', to='authentication.profile')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='book.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book.genre'),
        ),
    ]
